e2e: add test for dynamic balloons configuration update
intel/cri-resource-manager pull request #831
Opened 2022-06-10 10:08 UTC by askervin

- Add new test that changes balloons and CPU configurations using a
  config map.
- Refactor verify-metrics functions to a common source file.

2022-06-10 10:08 UTC, askervin commented
Needs balloons configuration update patch from PR #830.

2022-06-17 11:38 UTC, klihub requested changes

2022-06-17 11:38 UTC, klihub commented on test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh
> +}
Hmm... shouldn't it be something like:

```
cleanup() {
    vm-command "kubectl delete pods --all --now; \
        kubectl delete pods -n $testns --all --now; \
        kubectl delete pods -n btype1ns0 --all --now; \
        kubectl delete namespace $testns || :; \
        kubectl delete namespace btype1ns0 || :"
    terminate cri-resmgr
    terminate cri-resmgr-agent
    vm-command "cri-resmgr -reset-policy; cri-resmgr -reset-config"
}

apply-configmap() {
    vm-put-file $(instantiate balloons-configmap.yaml) balloons-configmap.yaml
    vm-command "cat balloons-configmap.yaml"
    vm-command "kubectl apply -f balloons-configmap.yaml"
}
```

2022-06-17 11:43 UTC, klihub commented on test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh
> +verify-metrics-has-line 'btype2\[0\].*pod2:pod2c0.*cpu_class="classB"'
And do a final
```
cleanup
```

here at the end too, please.

2022-06-17 17:10 UTC, klihub commented on test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh
> +    kubectl apply -f balloons-configmap.yaml
Hmm... isn't this still wrong ? Shouldn't it be `vm-command "kubectl apply -f balloons-configmap.yaml"`

2022-06-17 17:16 UTC, klihub commented on test/e2e/policies.test-suite/balloons/n4c16/test06-update-configmap/code.var.sh
> +    kubectl apply -f balloons-configmap.yaml
Okay, I see. We have a `kubectl()` wrapper shell function defined in `run.sh`. I have to say, the way how we use both that and also `vm-command "kubectl..."`'s is totally super-confusing... We should at least try to be more consistent with these.

2022-06-17 19:57 UTC, klihub approved these changes
LGTM

2022-06-20 06:06 UTC, merged